import { useState } from "react";
import { ArrowLeft, Share2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ClaimForm } from "./claim-form";
import { maskIdentifier, safeArea } from "./mask";
import type { FoundItem } from "./lost-found-grid";

export function ItemDetailSheet({ item, onClose }: { item: FoundItem | null; onClose: () => void }) {
  const [claiming, setClaiming] = useState(false);
  if (!item) return null;
  const share = async () => { if (navigator.share) await navigator.share({ title: `Lost & Found: ${item.item_type}`, text: `Found item in ${safeArea(item.location_text, item.district)}` }); else await navigator.clipboard?.writeText(window.location.href); };
  return <div className="fixed inset-0 z-50 flex items-end bg-black/50 p-3 backdrop-blur-sm sm:items-center sm:justify-center" onClick={onClose}><div className="max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-3xl border border-border/70 bg-background p-5 shadow-2xl sm:p-7" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">Found item</p><button type="button" onClick={onClose} aria-label="Close" className="grid h-9 w-9 place-items-center rounded-lg hover:bg-accent"><X className="h-4 w-4" /></button></div><h2 className="mt-4 font-display text-2xl font-black capitalize">{item.item_type}</h2><p className="mt-2 text-[13px] leading-relaxed text-muted-foreground">{item.description || "Safe details are withheld. Describe what makes this item yours."}</p><div className="mt-5 space-y-2 border-y border-border/60 py-4 text-[12px]"><p><span className="text-muted-foreground">Area</span><span className="float-right font-semibold">{safeArea(item.location_text, item.district)}</span></p><p><span className="text-muted-foreground">Handed in</span><span className="float-right font-semibold">{new Date(item.created_at).toLocaleDateString("en-UG")}</span></p>{item.identifier && <p><span className="text-muted-foreground">Reference</span><span className="float-right font-semibold">{maskIdentifier(item.identifier)}</span></p>}</div>{claiming ? <div className="mt-6"><button type="button" onClick={() => setClaiming(false)} className="mb-4 inline-flex items-center gap-2 text-[12px] font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Back</button><ClaimForm itemId={item.id} onDone={onClose} /></div> : <div className="mt-6 grid gap-2"><Button type="button" onClick={() => setClaiming(true)} className="h-12 rounded-xl">This is mine — claim it</Button><Button type="button" variant="outline" onClick={() => void share()} className="h-12 rounded-xl"><Share2 className="mr-2 h-4 w-4" /> Share</Button></div>}</div></div>;
}
