/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SosRouteImport } from './routes/sos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sos': typeof SosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sos': typeof SosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sos': typeof SosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sos'
    | '/dashboard'
    | '/api/chat'
    | '/api/transcribe'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sos'
    | '/dashboard'
    | '/api/chat'
    | '/api/transcribe'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sos'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/api/transcribe'
    | '/_authenticated/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SosRoute: typeof SosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SosRoute: SosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
