/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as SosRouteImport } from './routes/sos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPoliceRouteImport } from './routes/_authenticated/police'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedPoliceIndexRouteImport } from './routes/_authenticated/police.index'
import { Route as AuthenticatedPoliceDispatchRouteImport } from './routes/_authenticated/police.dispatch'
import { Route as AuthenticatedPoliceIncidentsRouteImport } from './routes/_authenticated/police.incidents'
import { Route as AuthenticatedPoliceMapRouteImport } from './routes/_authenticated/police.map'
import { Route as AuthenticatedPoliceOfficersRouteImport } from './routes/_authenticated/police.officers'
import { Route as AuthenticatedPolicePersonsRouteImport } from './routes/_authenticated/police.persons'
import { Route as AuthenticatedPoliceCasesCaseIdRouteImport } from './routes/_authenticated/police.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliceRoute = AuthenticatedPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliceIndexRoute =
  AuthenticatedPoliceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceDispatchRoute =
  AuthenticatedPoliceDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceIncidentsRoute =
  AuthenticatedPoliceIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceMapRoute = AuthenticatedPoliceMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedPoliceRoute,
} as any)
const AuthenticatedPoliceOfficersRoute =
  AuthenticatedPoliceOfficersRouteImport.update({
    id: '/officers',
    path: '/officers',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPolicePersonsRoute =
  AuthenticatedPolicePersonsRouteImport.update({
    id: '/persons',
    path: '/persons',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceCasesCaseIdRoute =
  AuthenticatedPoliceCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/sos': typeof SosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/police': typeof AuthenticatedPoliceRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/police/map': typeof AuthenticatedPoliceMapRoute
  '/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/police/': typeof AuthenticatedPoliceIndexRoute
  '/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/sos': typeof SosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/police/map': typeof AuthenticatedPoliceMapRoute
  '/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/police': typeof AuthenticatedPoliceIndexRoute
  '/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/nearby': typeof NearbyRoute
  '/sos': typeof SosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/police': typeof AuthenticatedPoliceRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/_authenticated/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/_authenticated/police/map': typeof AuthenticatedPoliceMapRoute
  '/_authenticated/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/_authenticated/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/police/': typeof AuthenticatedPoliceIndexRoute
  '/_authenticated/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/nearby'
    | '/sos'
    | '/dashboard'
    | '/police'
    | '/profile'
    | '/reports'
    | '/api/chat'
    | '/api/transcribe'
    | '/chat/$threadId'
    | '/police/dispatch'
    | '/police/incidents'
    | '/police/map'
    | '/police/officers'
    | '/police/persons'
    | '/chat/'
    | '/police/'
    | '/police/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/nearby'
    | '/sos'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/api/chat'
    | '/api/transcribe'
    | '/chat/$threadId'
    | '/police/dispatch'
    | '/police/incidents'
    | '/police/map'
    | '/police/officers'
    | '/police/persons'
    | '/chat'
    | '/police'
    | '/police/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/auth'
    | '/nearby'
    | '/sos'
    | '/_authenticated/dashboard'
    | '/_authenticated/police'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/api/chat'
    | '/api/transcribe'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/police/dispatch'
    | '/_authenticated/police/incidents'
    | '/_authenticated/police/map'
    | '/_authenticated/police/officers'
    | '/_authenticated/police/persons'
    | '/_authenticated/chat/'
    | '/_authenticated/police/'
    | '/_authenticated/police/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  NearbyRoute: typeof NearbyRoute
  SosRoute: typeof SosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police': {
      id: '/_authenticated/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof AuthenticatedPoliceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police/': {
      id: '/_authenticated/police/'
      path: '/'
      fullPath: '/police/'
      preLoaderRoute: typeof AuthenticatedPoliceIndexRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/dispatch': {
      id: '/_authenticated/police/dispatch'
      path: '/dispatch'
      fullPath: '/police/dispatch'
      preLoaderRoute: typeof AuthenticatedPoliceDispatchRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/incidents': {
      id: '/_authenticated/police/incidents'
      path: '/incidents'
      fullPath: '/police/incidents'
      preLoaderRoute: typeof AuthenticatedPoliceIncidentsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/map': {
      id: '/_authenticated/police/map'
      path: '/map'
      fullPath: '/police/map'
      preLoaderRoute: typeof AuthenticatedPoliceMapRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/officers': {
      id: '/_authenticated/police/officers'
      path: '/officers'
      fullPath: '/police/officers'
      preLoaderRoute: typeof AuthenticatedPoliceOfficersRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/persons': {
      id: '/_authenticated/police/persons'
      path: '/persons'
      fullPath: '/police/persons'
      preLoaderRoute: typeof AuthenticatedPolicePersonsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/cases/$caseId': {
      id: '/_authenticated/police/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/police/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedPoliceCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
  }
}

interface AuthenticatedPoliceRouteChildren {
  AuthenticatedPoliceDispatchRoute: typeof AuthenticatedPoliceDispatchRoute
  AuthenticatedPoliceIncidentsRoute: typeof AuthenticatedPoliceIncidentsRoute
  AuthenticatedPoliceMapRoute: typeof AuthenticatedPoliceMapRoute
  AuthenticatedPoliceOfficersRoute: typeof AuthenticatedPoliceOfficersRoute
  AuthenticatedPolicePersonsRoute: typeof AuthenticatedPolicePersonsRoute
  AuthenticatedPoliceIndexRoute: typeof AuthenticatedPoliceIndexRoute
  AuthenticatedPoliceCasesCaseIdRoute: typeof AuthenticatedPoliceCasesCaseIdRoute
}

const AuthenticatedPoliceRouteChildren: AuthenticatedPoliceRouteChildren = {
  AuthenticatedPoliceDispatchRoute: AuthenticatedPoliceDispatchRoute,
  AuthenticatedPoliceIncidentsRoute: AuthenticatedPoliceIncidentsRoute,
  AuthenticatedPoliceMapRoute: AuthenticatedPoliceMapRoute,
  AuthenticatedPoliceOfficersRoute: AuthenticatedPoliceOfficersRoute,
  AuthenticatedPolicePersonsRoute: AuthenticatedPolicePersonsRoute,
  AuthenticatedPoliceIndexRoute: AuthenticatedPoliceIndexRoute,
  AuthenticatedPoliceCasesCaseIdRoute: AuthenticatedPoliceCasesCaseIdRoute,
}

const AuthenticatedPoliceRouteWithChildren =
  AuthenticatedPoliceRoute._addFileChildren(AuthenticatedPoliceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPoliceRoute: typeof AuthenticatedPoliceRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPoliceRoute: AuthenticatedPoliceRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  NearbyRoute: NearbyRoute,
  SosRoute: SosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
