/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SosRouteImport } from './routes/sos'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPoliceRouteImport } from './routes/_authenticated/police'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedResponderRouteImport } from './routes/_authenticated/responder'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedPoliceIndexRouteImport } from './routes/_authenticated/police.index'
import { Route as AuthenticatedPoliceAiRouteImport } from './routes/_authenticated/police.ai'
import { Route as AuthenticatedPoliceAlertsRouteImport } from './routes/_authenticated/police.alerts'
import { Route as AuthenticatedPoliceAnalyticsRouteImport } from './routes/_authenticated/police.analytics'
import { Route as AuthenticatedPoliceAuditRouteImport } from './routes/_authenticated/police.audit'
import { Route as AuthenticatedPoliceAuthorityRouteImport } from './routes/_authenticated/police.authority'
import { Route as AuthenticatedPoliceCommsRouteImport } from './routes/_authenticated/police.comms'
import { Route as AuthenticatedPoliceDispatchRouteImport } from './routes/_authenticated/police.dispatch'
import { Route as AuthenticatedPoliceIncidentsRouteImport } from './routes/_authenticated/police.incidents'
import { Route as AuthenticatedPoliceMapRouteImport } from './routes/_authenticated/police.map'
import { Route as AuthenticatedPoliceOfficersRouteImport } from './routes/_authenticated/police.officers'
import { Route as AuthenticatedPolicePersonsRouteImport } from './routes/_authenticated/police.persons'
import { Route as AuthenticatedPoliceSearchRouteImport } from './routes/_authenticated/police.search'
import { Route as AuthenticatedPoliceSettingsRouteImport } from './routes/_authenticated/police.settings'
import { Route as AuthenticatedPoliceCasesCaseIdRouteImport } from './routes/_authenticated/police.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliceRoute = AuthenticatedPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponderRoute = AuthenticatedResponderRouteImport.update({
  id: '/responder',
  path: '/responder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliceIndexRoute =
  AuthenticatedPoliceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceAiRoute = AuthenticatedPoliceAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedPoliceRoute,
} as any)
const AuthenticatedPoliceAlertsRoute =
  AuthenticatedPoliceAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceAnalyticsRoute =
  AuthenticatedPoliceAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceAuditRoute =
  AuthenticatedPoliceAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceAuthorityRoute =
  AuthenticatedPoliceAuthorityRouteImport.update({
    id: '/authority',
    path: '/authority',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceCommsRoute =
  AuthenticatedPoliceCommsRouteImport.update({
    id: '/comms',
    path: '/comms',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceDispatchRoute =
  AuthenticatedPoliceDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceIncidentsRoute =
  AuthenticatedPoliceIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceMapRoute = AuthenticatedPoliceMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedPoliceRoute,
} as any)
const AuthenticatedPoliceOfficersRoute =
  AuthenticatedPoliceOfficersRouteImport.update({
    id: '/officers',
    path: '/officers',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPolicePersonsRoute =
  AuthenticatedPolicePersonsRouteImport.update({
    id: '/persons',
    path: '/persons',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceSearchRoute =
  AuthenticatedPoliceSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceSettingsRoute =
  AuthenticatedPoliceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)
const AuthenticatedPoliceCasesCaseIdRoute =
  AuthenticatedPoliceCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedPoliceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/sos': typeof SosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/police': typeof AuthenticatedPoliceRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/responder': typeof AuthenticatedResponderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/police/ai': typeof AuthenticatedPoliceAiRoute
  '/police/alerts': typeof AuthenticatedPoliceAlertsRoute
  '/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/police/audit': typeof AuthenticatedPoliceAuditRoute
  '/police/authority': typeof AuthenticatedPoliceAuthorityRoute
  '/police/comms': typeof AuthenticatedPoliceCommsRoute
  '/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/police/map': typeof AuthenticatedPoliceMapRoute
  '/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/police/search': typeof AuthenticatedPoliceSearchRoute
  '/police/settings': typeof AuthenticatedPoliceSettingsRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/police/': typeof AuthenticatedPoliceIndexRoute
  '/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/sos': typeof SosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/responder': typeof AuthenticatedResponderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/police/ai': typeof AuthenticatedPoliceAiRoute
  '/police/alerts': typeof AuthenticatedPoliceAlertsRoute
  '/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/police/audit': typeof AuthenticatedPoliceAuditRoute
  '/police/authority': typeof AuthenticatedPoliceAuthorityRoute
  '/police/comms': typeof AuthenticatedPoliceCommsRoute
  '/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/police/map': typeof AuthenticatedPoliceMapRoute
  '/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/police/search': typeof AuthenticatedPoliceSearchRoute
  '/police/settings': typeof AuthenticatedPoliceSettingsRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/police': typeof AuthenticatedPoliceIndexRoute
  '/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/sos': typeof SosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/police': typeof AuthenticatedPoliceRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/responder': typeof AuthenticatedResponderRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/voice': typeof ApiVoiceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/police/ai': typeof AuthenticatedPoliceAiRoute
  '/_authenticated/police/alerts': typeof AuthenticatedPoliceAlertsRoute
  '/_authenticated/police/analytics': typeof AuthenticatedPoliceAnalyticsRoute
  '/_authenticated/police/audit': typeof AuthenticatedPoliceAuditRoute
  '/_authenticated/police/authority': typeof AuthenticatedPoliceAuthorityRoute
  '/_authenticated/police/comms': typeof AuthenticatedPoliceCommsRoute
  '/_authenticated/police/dispatch': typeof AuthenticatedPoliceDispatchRoute
  '/_authenticated/police/incidents': typeof AuthenticatedPoliceIncidentsRoute
  '/_authenticated/police/map': typeof AuthenticatedPoliceMapRoute
  '/_authenticated/police/officers': typeof AuthenticatedPoliceOfficersRoute
  '/_authenticated/police/persons': typeof AuthenticatedPolicePersonsRoute
  '/_authenticated/police/search': typeof AuthenticatedPoliceSearchRoute
  '/_authenticated/police/settings': typeof AuthenticatedPoliceSettingsRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/police/': typeof AuthenticatedPoliceIndexRoute
  '/_authenticated/police/cases/$caseId': typeof AuthenticatedPoliceCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/mcp'
    | '/nearby'
    | '/onboarding'
    | '/sos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calls'
    | '/dashboard'
    | '/police'
    | '/profile'
    | '/reports'
    | '/responder'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/voice'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/police/ai'
    | '/police/alerts'
    | '/police/analytics'
    | '/police/audit'
    | '/police/authority'
    | '/police/comms'
    | '/police/dispatch'
    | '/police/incidents'
    | '/police/map'
    | '/police/officers'
    | '/police/persons'
    | '/police/search'
    | '/police/settings'
    | '/chat/'
    | '/police/'
    | '/police/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/mcp'
    | '/nearby'
    | '/onboarding'
    | '/sos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/calls'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/responder'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/voice'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/police/ai'
    | '/police/alerts'
    | '/police/analytics'
    | '/police/audit'
    | '/police/authority'
    | '/police/comms'
    | '/police/dispatch'
    | '/police/incidents'
    | '/police/map'
    | '/police/officers'
    | '/police/persons'
    | '/police/search'
    | '/police/settings'
    | '/chat'
    | '/police'
    | '/police/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/auth'
    | '/mcp'
    | '/nearby'
    | '/onboarding'
    | '/sos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/calls'
    | '/_authenticated/dashboard'
    | '/_authenticated/police'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/responder'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/voice'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/police/ai'
    | '/_authenticated/police/alerts'
    | '/_authenticated/police/analytics'
    | '/_authenticated/police/audit'
    | '/_authenticated/police/authority'
    | '/_authenticated/police/comms'
    | '/_authenticated/police/dispatch'
    | '/_authenticated/police/incidents'
    | '/_authenticated/police/map'
    | '/_authenticated/police/officers'
    | '/_authenticated/police/persons'
    | '/_authenticated/police/search'
    | '/_authenticated/police/settings'
    | '/_authenticated/chat/'
    | '/_authenticated/police/'
    | '/_authenticated/police/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  NearbyRoute: typeof NearbyRoute
  OnboardingRoute: typeof OnboardingRoute
  SosRoute: typeof SosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police': {
      id: '/_authenticated/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof AuthenticatedPoliceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responder': {
      id: '/_authenticated/responder'
      path: '/responder'
      fullPath: '/responder'
      preLoaderRoute: typeof AuthenticatedResponderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/police/': {
      id: '/_authenticated/police/'
      path: '/'
      fullPath: '/police/'
      preLoaderRoute: typeof AuthenticatedPoliceIndexRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/ai': {
      id: '/_authenticated/police/ai'
      path: '/ai'
      fullPath: '/police/ai'
      preLoaderRoute: typeof AuthenticatedPoliceAiRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/alerts': {
      id: '/_authenticated/police/alerts'
      path: '/alerts'
      fullPath: '/police/alerts'
      preLoaderRoute: typeof AuthenticatedPoliceAlertsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/analytics': {
      id: '/_authenticated/police/analytics'
      path: '/analytics'
      fullPath: '/police/analytics'
      preLoaderRoute: typeof AuthenticatedPoliceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/audit': {
      id: '/_authenticated/police/audit'
      path: '/audit'
      fullPath: '/police/audit'
      preLoaderRoute: typeof AuthenticatedPoliceAuditRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/authority': {
      id: '/_authenticated/police/authority'
      path: '/authority'
      fullPath: '/police/authority'
      preLoaderRoute: typeof AuthenticatedPoliceAuthorityRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/comms': {
      id: '/_authenticated/police/comms'
      path: '/comms'
      fullPath: '/police/comms'
      preLoaderRoute: typeof AuthenticatedPoliceCommsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/dispatch': {
      id: '/_authenticated/police/dispatch'
      path: '/dispatch'
      fullPath: '/police/dispatch'
      preLoaderRoute: typeof AuthenticatedPoliceDispatchRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/incidents': {
      id: '/_authenticated/police/incidents'
      path: '/incidents'
      fullPath: '/police/incidents'
      preLoaderRoute: typeof AuthenticatedPoliceIncidentsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/map': {
      id: '/_authenticated/police/map'
      path: '/map'
      fullPath: '/police/map'
      preLoaderRoute: typeof AuthenticatedPoliceMapRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/officers': {
      id: '/_authenticated/police/officers'
      path: '/officers'
      fullPath: '/police/officers'
      preLoaderRoute: typeof AuthenticatedPoliceOfficersRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/persons': {
      id: '/_authenticated/police/persons'
      path: '/persons'
      fullPath: '/police/persons'
      preLoaderRoute: typeof AuthenticatedPolicePersonsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/search': {
      id: '/_authenticated/police/search'
      path: '/search'
      fullPath: '/police/search'
      preLoaderRoute: typeof AuthenticatedPoliceSearchRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/settings': {
      id: '/_authenticated/police/settings'
      path: '/settings'
      fullPath: '/police/settings'
      preLoaderRoute: typeof AuthenticatedPoliceSettingsRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
    '/_authenticated/police/cases/$caseId': {
      id: '/_authenticated/police/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/police/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedPoliceCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedPoliceRoute
    }
  }
}

interface AuthenticatedPoliceRouteChildren {
  AuthenticatedPoliceAiRoute: typeof AuthenticatedPoliceAiRoute
  AuthenticatedPoliceAlertsRoute: typeof AuthenticatedPoliceAlertsRoute
  AuthenticatedPoliceAnalyticsRoute: typeof AuthenticatedPoliceAnalyticsRoute
  AuthenticatedPoliceAuditRoute: typeof AuthenticatedPoliceAuditRoute
  AuthenticatedPoliceAuthorityRoute: typeof AuthenticatedPoliceAuthorityRoute
  AuthenticatedPoliceCommsRoute: typeof AuthenticatedPoliceCommsRoute
  AuthenticatedPoliceDispatchRoute: typeof AuthenticatedPoliceDispatchRoute
  AuthenticatedPoliceIncidentsRoute: typeof AuthenticatedPoliceIncidentsRoute
  AuthenticatedPoliceMapRoute: typeof AuthenticatedPoliceMapRoute
  AuthenticatedPoliceOfficersRoute: typeof AuthenticatedPoliceOfficersRoute
  AuthenticatedPolicePersonsRoute: typeof AuthenticatedPolicePersonsRoute
  AuthenticatedPoliceSearchRoute: typeof AuthenticatedPoliceSearchRoute
  AuthenticatedPoliceSettingsRoute: typeof AuthenticatedPoliceSettingsRoute
  AuthenticatedPoliceIndexRoute: typeof AuthenticatedPoliceIndexRoute
  AuthenticatedPoliceCasesCaseIdRoute: typeof AuthenticatedPoliceCasesCaseIdRoute
}

const AuthenticatedPoliceRouteChildren: AuthenticatedPoliceRouteChildren = {
  AuthenticatedPoliceAiRoute: AuthenticatedPoliceAiRoute,
  AuthenticatedPoliceAlertsRoute: AuthenticatedPoliceAlertsRoute,
  AuthenticatedPoliceAnalyticsRoute: AuthenticatedPoliceAnalyticsRoute,
  AuthenticatedPoliceAuditRoute: AuthenticatedPoliceAuditRoute,
  AuthenticatedPoliceAuthorityRoute: AuthenticatedPoliceAuthorityRoute,
  AuthenticatedPoliceCommsRoute: AuthenticatedPoliceCommsRoute,
  AuthenticatedPoliceDispatchRoute: AuthenticatedPoliceDispatchRoute,
  AuthenticatedPoliceIncidentsRoute: AuthenticatedPoliceIncidentsRoute,
  AuthenticatedPoliceMapRoute: AuthenticatedPoliceMapRoute,
  AuthenticatedPoliceOfficersRoute: AuthenticatedPoliceOfficersRoute,
  AuthenticatedPolicePersonsRoute: AuthenticatedPolicePersonsRoute,
  AuthenticatedPoliceSearchRoute: AuthenticatedPoliceSearchRoute,
  AuthenticatedPoliceSettingsRoute: AuthenticatedPoliceSettingsRoute,
  AuthenticatedPoliceIndexRoute: AuthenticatedPoliceIndexRoute,
  AuthenticatedPoliceCasesCaseIdRoute: AuthenticatedPoliceCasesCaseIdRoute,
}

const AuthenticatedPoliceRouteWithChildren =
  AuthenticatedPoliceRoute._addFileChildren(AuthenticatedPoliceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPoliceRoute: typeof AuthenticatedPoliceRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResponderRoute: typeof AuthenticatedResponderRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPoliceRoute: AuthenticatedPoliceRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResponderRoute: AuthenticatedResponderRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  NearbyRoute: NearbyRoute,
  OnboardingRoute: OnboardingRoute,
  SosRoute: SosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
